### ISSUE TITLE
SignOut Needed

### ISSUE THREAD

**Issue by jindalAnuj** [krolmic/recipes_app#20]
Hi I am new to flutter and inherited widgets approach.  I have tried a lot but unable to add signOut method 
please help .
It will be great if you can add code to repo or post here.
Thanks in advance . 

@krolmic

**Comment by krolmic** [comment]
Hi @jindalAnuj,

I am glad that you are interested in Flutter and I hope that you have solved this issue in the meantime.

If you are looking for an approach on how to implement the sign-out, take a look at the article [Simple Recipes App made in Flutter — Detail View and Settings Widget](https://medium.com/flutter-community/simple-recipes-app-made-in-flutter-detail-view-and-settings-widget-9a7ca9ebec93).

Best regards
Michael
